<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rviz2_cinematographer_view_controller</name>
  <version>0.2.0</version>
  <description>An rviz2 view controller featuring smooth transitions along camera trajectories and frame-by-frame rendering for video recording.</description>

  <maintainer email="ms.kataoka@gmail.com">Masaya Kataoka</maintainer>

  <license>BSD-3-Clause</license>

  <url type="website">https://github.com/hakuturu583/rviz_cinematographer</url>
  <url type="repository">https://github.com/hakuturu583/rviz_cinematographer</url>
  <url type="bugtracker">https://github.com/hakuturu583/rviz_cinematographer/issues</url>

  <author email="adamleeper@gmail.com">Adam Leeper</author>
  <author email="razlaw@ais.uni-bonn.de">Jan Razlaw</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>qtbase5-dev</build_depend>
  <build_export_depend>qtbase5-dev</build_export_depend>
  <exec_depend>libqt5-core</exec_depend>
  <exec_depend>libqt5-widgets</exec_depend>

  <depend>rclcpp</depend>
  <depend>pluginlib</depend>
  <depend>rviz_common</depend>
  <depend>rviz_rendering</depend>
  <depend>rviz_ogre_vendor</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>image_transport</depend>
  <depend>rviz2_cinematographer_msgs</depend>

  <exec_depend>rviz2</exec_depend>
  <exec_depend>rviz_default_plugins</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
    <rviz_common plugin="${prefix}/plugin_description.xml"/>
  </export>
</package>
