<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rviz2_cinematographer_video_recorder</name>
  <version>0.2.0</version>
  <description>Subscribes to images rendered by the rviz2 cinematographer view controller and generates a video.</description>

  <maintainer email="ms.kataoka@gmail.com">Masaya Kataoka</maintainer>

  <license>BSD-3-Clause</license>

  <url type="website">https://github.com/hakuturu583/rviz_cinematographer</url>
  <url type="repository">https://github.com/hakuturu583/rviz_cinematographer</url>
  <url type="bugtracker">https://github.com/hakuturu583/rviz_cinematographer/issues</url>

  <author email="razlaw@ais.uni-bonn.de">Jan Razlaw</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>ament_index_cpp</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>cv_bridge</depend>
  <depend>image_transport</depend>
  <depend>sensor_msgs</depend>
  <depend>rviz2_cinematographer_msgs</depend>
  <depend>libopencv-dev</depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
