<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rviz2_cinematographer_msgs</name>
  <version>0.2.0</version>
  <description>Message definitions for the rviz2 cinematographer.</description>

  <maintainer email="ms.kataoka@gmail.com">Masaya Kataoka</maintainer>

  <license>BSD-3-Clause</license>

  <url type="website">https://github.com/hakuturu583/rviz_cinematographer</url>
  <url type="repository">https://github.com/hakuturu583/rviz_cinematographer</url>
  <url type="bugtracker">https://github.com/hakuturu583/rviz_cinematographer/issues</url>

  <author email="razlaw@ais.uni-bonn.de">Jan Razlaw</author>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <depend>builtin_interfaces</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>

  <exec_depend>rosidl_default_runtime</exec_depend>

  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
