<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rviz_cinematographer_gui</name>
  <version>0.2.0</version>
  <description>Manipulate the rviz camera using trajectories and record the resulting views. </description>
  <maintainer email="razlaw@ais.uni-bonn.de">Jan Razlaw</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>qtbase5-dev</build_depend>
  <build_export_depend>qtbase5-dev</build_export_depend>
  <exec_depend>libqt5-core</exec_depend>
  <exec_depend>libqt5-widgets</exec_depend>

  <depend>ament_index_cpp</depend>
  <depend>rclcpp</depend>
  <depend>pluginlib</depend>
  <depend>qt_gui_cpp</depend>
  <depend>rqt_gui_cpp</depend>
  <depend>interactive_markers</depend>
  <depend>tf2</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>std_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>rviz_cinematographer_msgs</depend>
  <depend>video_recorder</depend>
  <depend>yaml_cpp_vendor</depend>

  <exec_depend>rqt_gui</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>rviz_default_plugins</exec_depend>
  <exec_depend>rviz_cinematographer_view_controller</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
    <rqt_gui plugin="${prefix}/plugin.xml"/>
  </export>
</package>
